// Generated by CoffeeScript 1.8.0
var ColourPicker, Emitter, delegate,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Emitter = require('emitter');

delegate = require('delegate');

module.exports = ColourPicker = (function(_super) {
  __extends(ColourPicker, _super);

  function ColourPicker() {
    this.render = __bind(this.render, this);
    this.getTemplate = __bind(this.getTemplate, this);
    return ColourPicker.__super__.constructor.apply(this, arguments);
  }

  ColourPicker.prototype.palettes = [[['#FFFFFF', '#000000', '#EEECE1', "#1F497D", "#4F81BD", "#C0504D", "#9BBB59", "#8064A2", "#4BACC6", "#F79646"]], [['#F2F2F2', '#7F7F7F', '#DDD9C3', "#C6D9F0", "#DBE5F1", "#F2DCDB", "#EBF1DD", "#E5E0EC", "#DBEEF3", "#FDEADA"], ['#D8D8D8', '#595959', '#C4BD97', '#8DB3E2', '#B8CCE4', '#E5B9B7', '#D7E3BC', '#CCC1D9', '#B7DDE8', '#FBD5B5'], ['#BFBFBF', '#3F3F3F', '#938953', '#548DD4', '#95B3D6', '#D99694', '#C3D69B', '#B2A2C7', '#92CDDC', '#FAC08F'], ['#A5A5A5', '#262626', '#494429', '#17365D', '#366092', '#963A37', '#76923C', '#5F497A', '#31859B', '#E36C09'], ['#808080', '#0C0C0C', '#1D1B10', '#0F243E', '#244061', '#632423', '#4F6128', '#3F3151', '#205867', '#974806']], [['#FFFFFF', '#C0C0C0', '#FF0000', "#FFFF00", "#00FF00", "#00FFFF", "#0000FF", "#FF00FF"]], [['#000000', '#808080', '#800000', "#808000", "#008000", "#008080", "#000080", "#800080"]]];

  ColourPicker.prototype.getTemplate = function() {
    var colour, palette, swatch, template, _i, _j, _k, _ref, _ref1, _ref2;
    template = "<span class='colour-picker'>";
    if (this.useDefault === true) {
      template += "<div class='colour default'>Use Default</div>";
    }
    for (palette = _i = 0, _ref = this.palettes.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; palette = 0 <= _ref ? ++_i : --_i) {
      template += "<table>";
      for (swatch = _j = 0, _ref1 = this.palettes[palette].length - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; swatch = 0 <= _ref1 ? ++_j : --_j) {
        template += "<tr>";
        for (colour = _k = 0, _ref2 = this.palettes[palette][swatch].length - 1; 0 <= _ref2 ? _k <= _ref2 : _k >= _ref2; colour = 0 <= _ref2 ? ++_k : --_k) {
          template += "<td><div class='colour' style='background-color:" + this.palettes[palette][swatch][colour] + "'/></td>";
        }
        template += "</tr>";
      }
      template += "</table>";
    }
    template += "</span>";
    return template;
  };

  ColourPicker.prototype.render = function() {
    var el;
    el = document.createElement('div');
    el.innerHTML = this.getTemplate();
    delegate.bind(el, '.colour', 'click', (function(_this) {
      return function(e) {
        return _this.emit('picked', e.target.style.backgroundColor);
      };
    })(this), false);
    return el;
  };

  return ColourPicker;

})(Emitter);
